### ISSUE TITLE
Electric banner largest two pipe Error

### ISSUE THREAD

**Issue by alaminkawsar** [Anik-Modak/Interviews#1]
Electric banner largest two pipe problem solution should be little modified because it doesn't pass the following test case
```
1
4
3 4 7 8
```
output should be 7, but found 11.

Your code should be following modification:

```
if(p1==p2) {
        dp[p1][p2][i] = max(dp[p1][p2][i],p1);
        ans = max(ans,p1); // ans should be global and it is the ultimate answer.
}

```
thanks vai...);

**Comment by Anik-Modak** [comment]
Ei problem ta may be haker earth e chilo and accepted solution chilo. Sei
code e ki up ache kina sure na.

**Comment by alaminkawsar** [comment]
এটা অনেক খুজেছি ভাই পাই নাই। geeksforgeeks এ প্রব্লেমটা দেখেছিলাম। যাইহোক, আপনাকে অসংখ্য ধন্যবাদ ভাই, আপনার কোডগুলো আমাদের ব্যাচের সবাই প্র‍্যাক্টিস করতে পারছে এখন।
